# updates exiting bookdown for a repository
# deploys to a branch gh-pages
name: call-update-bookdown
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# this workflow runs on pushes to main or master
  push:
    branches: [main, master]
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/update-bookdown.yml@main
      with:
        bookdown-input: '.'
        bookdown-output_dir: '_book_built' # optional. Could remove. to use output_dir in _bookdown.yml
        deployment_dir: '_book'
