# document and style R code using reusable workflow
# runs devtools::document() and styler::style_active_package() to 
# runs r4ss:::rm_dollar_sign() in addition, which converts $ to '[[' in R code
name: call-doc-and-style-r
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# workflow_dispatch requires pushing a button to run the workflow manually. uncomment the following line to add:
  #workflow_dispatch:
  # Runs the workflow on each push to the main or master branch:
  push:
    branches: [main, master]
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/doc-and-style-r.yml@main
    with:
      run-rm_dollar_sign: true
