# use gitleaks (https://github.com/zricethezav/gitleaks) to check for accidentally committing secrets to your codebase.
name: call-run-geatleaks
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# workflow_dispatch requires pushing a button to run the workflow manually. uncomment the following line to add:
  #workflow_dispatch:
  # Runs the workflow on each push:
  push:
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/run-gitleaks.yml@main
