# document and style  using reusable workflow
# runs r4ss::rm_dollar_sign() in addition, which converts $ to '[[' in R code
on:
  workflow_dispatch:
  push:
    branches: [main]
name: call-doc-and-style-r
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/doc-and-style-r.yml@main
    with:
      run-rm_dollar_sign: true
