# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_call:
    inputs:
      additional_args_windows:
        required: false
        type: string
        default: ""
      additional_args_macos:
        required: false
        type: string
        default: ""
      additional_args_ubuntu:
        required: false
        type: string
        default: ""

name: build-pkgdown

# no permissions are needed by the default github token for this workflow to 
# run, so don't pass any.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}


jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - name: run additional args on windows
        if: matrix.config.os == 'windows-latest'
        run: ${{ inputs.additional_args_windows }}
      
      - name: run additional args on macOS
        if: matrix.config.os == 'macOS-latest'
        run: ${{ inputs.additional_args_macos }}
        
      - name: run additional args on ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: ${{ inputs.additional_args_ubuntu }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: build pkgdown
        run: |
          Rscript -e 'pkgdown::build_site()'
     
      - name: save pkgdown output
        uses: actions/upload-artifact@v4
        with:
          name: pkgdown-site
          path: docs/
     
