# Reusable workflow to calculate coverage; don't push to code cov.
# instead, use octocov, which allows all data to remain on github.

name: calc-covr-pr-octocov

on:
  workflow_call:

# limits permisions to write, as the common use case is for pull requests;
# this means certain options may not work, but makes the workflow more secure
permissions:
  pull-requests: write

jobs:
  calc-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2, any::htmltools, any::DT
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov, filename = "coverage.xml")
        shell: Rscript {0}
  
      - name:
        uses: k1LoW/octocov-action@v1


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report.xml
          path: ./coverage.xml