# document and style  using reusable workflow
on:
  push:
    branches: [permissions]

name: call-doc-and-style-r
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/doc-and-style-r.yml@permissions
