# Style DESCRIPTION file using reusable workflow
on:
  push:
    branches: [main]
    paths: 
      - 'DESCRIPTION'
name: call-style-description
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/style-description.yml@main
