# Run r cmd check
on:
  push:
  schedule:
    # This should run the default branch weekly on sunday
    - cron: '0 0 * * 0'
name: call-r-cmd-check

jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
    with:
      use_full_build_matrix: true
