# This action publishes to connect using the git-backed workflow. Note that
# it is only necessary to do it this way if the product is in a private or
# internal repository; otherwise, it is far easier to deploy following the
# instructions in https://docs.posit.co/connect/user/git-backed/

# To use this workflow, the user will need to generate the manifest.json, and 
# add 2 secrets, one named
# CONNECT_URL containing the connect url (complete with https:// in front of
# the address) and one named CONNECT_API_KEY, containing an API Key from connect.
# See  https://docs.posit.co/connect/user/api-keys/#api-keys-creating for
# instructions on creating an API key from connect and
# https://octopus.com/blog/githubactions-secrets for instructions on creating
# secrets
name: connect-publish
on:
  workflow_call:
    secrets:
      CONNECT_URL:
        required: true
      CONNECT_API_KEY:
        required: true

jobs:
  connect-publish:
    runs-on: 	ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
