# Reusable workflow for R-CMD-check
# based on https://github.com/r-lib/actions/blob/v2/examples/check-full.yaml

on:
  workflow_call:
    inputs:
      use_full_build_matrix:
        required: false
        type: boolean
      gha_timeout_minutes:
        required: false
        type: number
        default: 360
      depends_on_tmb:
        required: false
        type: boolean
        default: false
      depends_on_quarto:
        required: false
        type: boolean
        default: false
      additional_args_windows:
        required: false
        type: string
        default: ""
      additional_args_macos:
        required: false
        type: string
        default: ""
      additional_args_ubuntu:
        required: false
        type: string
        default: ""

# no permissions are needed by the default github token for this workflow to 
# run, so don't pass any.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

name: R-CMD-check
jobs:
  matrix_prep:
  # Determine the build matrix (OS and versions of R)
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'nmfs-ost/ghactions4r'
        ref: 'main'
    - name: check path
      run: |
        ls -r
        pwd
    - id: set-matrix
      run: |
        if ${{ inputs.use_full_build_matrix }} == 'true';
        then
          JSON=$(cat ./github/matrix_includes_full.json)
        else
          JSON=$(cat ./github/matrix_includes_standard.json)
        fi
        # note: if users were inputting the $JSON info, would want to 
        # randomize the delimiter. See 
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        echo 'matrix<<EOF' >> $GITHUB_OUTPUT
        echo "$JSON">> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

  R-CMD-check:
    needs: matrix_prep
    runs-on: ${{matrix.config.os }}
    timeout-minutes: ${{ inputs.gha_timeout_minutes }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      
      - name: run additional args on windows
        if: matrix.config.os == 'windows-latest'
        run: ${{ inputs.additional_args_windows }}
      
      - name: run additional args on macOS
        if: matrix.config.os == 'macOS-latest'
        run: ${{ inputs.additional_args_macos }}
        
      - name: run additional args on ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: ${{ inputs.additional_args_ubuntu }}
        
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: If dependent on TMB, install Matrix from source for windows and mac
        if: inputs.depends_on_tmb == true && runner.os != 'Linux'
        run: install.packages("Matrix", type = "source")
        shell: Rscript {0}

      - name: If depends on quarto, install.
        if: inputs.depends_on_quarto == true
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
