# check spelling using spelling::spell_check_package()
on:
  workflow_call:
    inputs:
      folder-path:
        required: true
        type: string
        default: '.'

name: render quarto and save as artifact
jobs:
  render-quarto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # note: may want to replace render quarto with just calling quarto render on the command line.
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: folder-path
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: quarto-output
          path: folder-path
