# check spelling using devtools::spell_check()
on:
 workflow_call:

name: run devtools::spell_check

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install spelling
        run: Rscript -e 'install.packages("spelling")'

      - name: spell check
        run: spelling::spell_check_package()
        shell: Rscript {0}

#      - name: fail job if any spelling errors are caught
