# This action runs styler::style_pkg() to style r code in an r pkg's repo. After
# styling, the changes are committed and a pull request to the branch the Workflow
# was started on is opened - this PR contains the commit.

# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
 workflow_call:

name: style r code with styler

jobs:
  style:
    name: style
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: Rscript -e 'install.packages("styler")'

      - name: Style
        run: | 
          results <- styler::style_pkg()
          # error if styler failed on any files
          if(any(is.na(results[["changed"]]))) {
            stop("styler threw an error")
          }
        shell: Rscript {0}
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'style: run styler::style_pkg()'
          branch: style-code
          title: 'Style code'
          body: |
           Auto-generated by [style-r-code.yml][1]

            [1]: https://github.com/nmfs-fish-tools/ghactions4r/tree/main/.github/workflows/style-r-code.yml

