# This action run devtools::document() then commits the changes to a commit and
# opens a pull request to the branch it was started from.

# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
 workflow_call:

name: update oxygen docs

jobs:
  document:
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: roxygen2

      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()' # devtools::document runs this

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Docs: run devtools::document()'
          branch: update-docs
          title: 'Update Roxygen documentation'
          body: |
           Auto-generated by [update-roxygen-docs.yml][1]

            [1]: https://github.com/nmfs-stock-synthesis/workflows/tree/main/.github/workflows/update-roxygen-docs.yml
